### ISSUE TITLE
Add/Display where Sprint / KOM / Reverse  are located ?

### ISSUE THREAD

**Issue by VNT974** [sandermvanvliet/RoadCaptain#10]
Hello.

Would it be possible to display where Sprint / Kom / Reverse are located on the map (which doesnt have Zwift world background yet if I understand) ? That way it would be interesting to select / manage a route with what we want to achieve.

Thanks.

**Comment by VNT974** [comment]
Hello. I totally understand, I do know this Internet Browser who use Zwift maps as background for Strava, probably can worth to know if they indeed asked Zwift to do it. https://github.com/andipaetzold/zwiftmap

**Comment by sandermvanvliet** [comment]
Yeah I've spoken with them earlier on Reddit, didn't ask about it but I can reach out to see if they got approval for it.

**Comment by sandermvanvliet** [comment]
Closing this in favour of #31 to track improvements to the map view where this is included.
