### ISSUE TITLE
Failed to decrypt message

### ISSUE THREAD

**Issue by PhilipAmos** [sandermvanvliet/RoadCaptain#107]
**Describe the issue**
Describe on what segment the turn was missed and if/what you did to try and get back on track.

**Application details:**
To help troubleshoot the issue please provide:
- Zwift version - Latest Version
- Zwift device - PC
- Road Captain version - Latest preview

I have found that Road Captain will run fine if it can get past the first few KM's.   Today I tried 6 times and I had 4 failures and a couple of times it ran nicely for a prolonged time.

When it goes wrong I see the following in the RoadCaptain Log:
2022-10-16 10:36:58.463 +01:00 [ERR] Failed to decrypt message

And the following in the Zwift Log:
[10:36:58] NETCLIENT:[ERROR] Auxiliary Controller received 'End of file' (2) during message length receive handler
[10:36:58] NETCLIENT:[INFO] Auxiliary Controller shutting down keep alive loop
[10:36:58] NETCLIENT:[INFO] Auxiliary Controller attempting to connect to phone at: 192.168.1.240:21588 (secure)

I did some playing around with the Windows Firewall logs and there isn't any traffic being blocked and even with the Firewall Log disabled this error can still occur and other times it won't.  In my instance its always at the start of a ride and just before the error I see this in the Zwift Logs where Zwift is moving between segments.

[10:36:57] ===========================================================
[10:36:57] [ActiveSegments] detected state change...
[10:36:57] Removed segment: 1065066326
[10:36:57] Added segment: 5353681768
[10:36:57] ==Current Active Segment Hash Ids==
[10:36:57] 5353681768
[10:36:57] ===========================================================

I have uploaded the logs for a couple of the failure from todays testing.

[0953 roadcaptain-runner-log-2022-10-16T084318.log](https://github.com/sandermvanvliet/RoadCaptain/files/9795508/0953.roadcaptain-runner-log-2022-10-16T084318.log)
[0953 Log.txt](https://github.com/sandermvanvliet/RoadCaptain/files/9795509/0953.Log.txt)
[1036 roadcaptain-runner-log-2022-10-16T093031.log](https://github.com/sandermvanvliet/RoadCaptain/files/9795482/1036.roadcaptain-runner-log-2022-10-16T093031.log)
[1036 Log.txt](https://github.com/sandermvanvliet/RoadCaptain/files/9795483/1036.Log.txt)
[1036 positions-2022-10-16_093151.log](https://github.com/sandermvanvliet/RoadCaptain/files/9795484/1036.positions-2022-10-16_093151.log)

**Comment by sandermvanvliet** [comment]
As you may have noticed I didn't have a lot of time to look into this issue.
However I did make some changes (see 1bf55d75201186171d482bf52832877671daf4c1) to make the decryption more robust and forgiving if it finds unexpected data.

It doesn't address all the issues you're seeing but at the same time I also have a hard time reproducing these kinds of issues.

**Comment by PhilipAmos** [comment]
I have tested a couple of times with the new  0.6.9.0 release and it did fail when running the attached route.  The Road Captain window went red where it lost connection, something else was displayed and then it reconnected but was saying "Ride to start of the route, keep pedaling".

So it looks like it recovered the connection but it lost track of where I was on the Route and wanted to pick up from the beginning.

[To Epic Divert.txt](https://github.com/sandermvanvliet/RoadCaptain/files/9970041/To.Epic.Divert.txt)
[roadcaptain-runner-log-2022-11-07T104841.log](https://github.com/sandermvanvliet/RoadCaptain/files/9970043/roadcaptain-runner-log-2022-11-07T104841.log)

**Comment by PhilipAmos** [comment]
I have tested a couple of times with the new  0.6.9.0 release and it did fail when running the attached route.  The Road Captain window went red where it lost connection, something else was displayed and then it reconnected but was saying "Ride to start of the route, keep pedaling".

So it looks like it recovered the connection but it lost track of where I was on the Route and wanted to pick up from the beginning.

[To Epic Divert.txt](https://github.com/sandermvanvliet/RoadCaptain/files/9970041/To.Epic.Divert.txt)
[roadcaptain-runner-log-2022-11-07T104841.log](https://github.com/sandermvanvliet/RoadCaptain/files/9970043/roadcaptain-runner-log-2022-11-07T104841.log)

**Comment by sandermvanvliet** [comment]
@PhilipAmos I think I may have found the issue as part of #111 
I'm putting out a new release that has a fix, would be great if you could test that and see if your problem has been resolved 👍

**Comment by PhilipAmos** [comment]
I have run 2 quick tests and there is still an issue.  I got the red screen where it lost connection and both times it re-made the connection within 2 miles.  The problem is that RoadRunner was then not able to continue on the course as it was saying start riding on Pega Pretzel.

[roadcaptain-runner-log-2023-01-09T200955.log](https://github.com/sandermvanvliet/RoadCaptain/files/10376574/roadcaptain-runner-log-2023-01-09T200955.log)
[roadcaptain-runner-log-2023-01-09T195940.log](https://github.com/sandermvanvliet/RoadCaptain/files/10376575/roadcaptain-runner-log-2023-01-09T195940.log)
[Route I as Following.txt](https://github.com/sandermvanvliet/RoadCaptain/files/10376605/Route.I.as.Following.txt)

**Comment by sandermvanvliet** [comment]
That was quick! Thanks for the additional info 👍

**Comment by sandermvanvliet** [comment]
@PhilipAmos I *think* I've got a possible solution for the route resume problem. It currently will pick up if you're on the segment you've left off or the next one, I think that's a wide enough margin not to cause any problems.

Let me know if that works for you!

**Comment by sandermvanvliet** [comment]
I’ve had the disconnect happen to me a few times yesterday mid-route and it recovered fine 👍
