### ISSUE TITLE
RouteBuilder local save triggers Zwift login

### ISSUE THREAD

**Issue by pwsouth** [sandermvanvliet/RoadCaptain#120]
When saving a route locally, the window opens to log in to Zwift. Is that intentional? This seems unnecessary and if I close the login window the route is successfully saved locally. Since pasting passwords doesn't work on macOS, it's burdensome to have to log in when it's apparently not needed. This is in 0.7.0.3.

**Comment by sandermvanvliet** [comment]
Definitely not intentional, this is a bug. 

Thanks for reporting it 👍

**Comment by sandermvanvliet** [comment]
This is fixed now, I'm pushing a new pre-release build soon.

**Comment by sandermvanvliet** [comment]
Release ought to be ready for download in the next 15 mins or so: https://github.com/sandermvanvliet/RoadCaptain/releases/tag/prerelease%2F0.7.0.4
