### ISSUE TITLE
Missing turn from Bridge Sprint

### ISSUE THREAD

**Issue by sandermvanvliet** [sandermvanvliet/RoadCaptain#128]
Just found another routing problem, a missing turn:
Segment _Bridge sprint to beach road_ (`watopia-bambino-fondo-001-after-after-after-after-before-after` is missing a left turn at its Southern end onto that newish shortcut segment _Italian villas loop 3_ (`watopia-beach-island-loop-004`).

https://github.com/sandermvanvliet/RoadCaptain/blob/a80ab43689ccda6d053a9f3644e55e5e802cd65a/src/RoadCaptain.Adapters/turns-watopia.json#L104

_Originally posted by @cwienands1 in https://github.com/sandermvanvliet/RoadCaptain/issues/126#issuecomment-1877575583_

**Comment by sandermvanvliet** [comment]
I need to check if this is a valid turn in-game, it wasn't before but with the latest updates it could be that you can make that left turn there.

**Comment by cwienands1** [comment]
I recently did a race that used that shortcut segment, but looking at the route, it approached the intersection from the other direction. I just hopped on the trainer, save you some time. That left turn, coming from the North actually is not possible in game, so you can close this issue (until Zwift enables it ;-)
