### ISSUE TITLE
Unable to select round-abouts in the desert

### ISSUE THREAD

**Issue by ph4r** [sandermvanvliet/RoadCaptain#13]
I am unable to figure out how to select the round-abouts / turn -arounds in the desert.  My goal was to start downtown, then head into tempist fugit and do laps there so that my warm-up is done before I start doing laps on the timed segment for tempist fugit reverse.

**Comment by sandermvanvliet** [comment]
The loop at the end of Fuego Flats in the direction of big foot hills should work but afaik the other one is event only…
I still need to check that in game to be sure. Ut I think that’s why I didn’t add it as an option in route builder (even though it shows on the map)

**Comment by VNT974** [comment]
Do you mean that Event only route couldn't be added?

**Comment by sandermvanvliet** [comment]
RoadCaptain can only navigate you on segments of Watopia that you'd normally be able to ride on. 
That indeed means that if there is a segment that is event only you can't ride there because you can't reach them from the game. On Watopia there are only the start pens and this bit on Fuego Flats are unreachable.

**Comment by sandermvanvliet** [comment]
Looking at the [Tempus Fugit](https://zwiftinsider.com/route/tempus-fugit/) route on Zwift insider it seems like it's a regular route but that I just didn't add the relevant turns in Road Captain.
I've added them so this loop should be possible to select now as of version 0.5.3.0.

**Comment by sandermvanvliet** [comment]
Word of warning: still need to verify it in game!
