### ISSUE TITLE
RoadCaptain Runner doesn't start

### ISSUE THREAD

**Issue by ph4r** [sandermvanvliet/RoadCaptain#14]
The first time I was prompted to install .Net 6.0 which I did, but now nothing happens when I attempt to start it.

**Comment by VNT974** [comment]
I generally restart computer and open RoadCaptain Route Builder, the other one didn't work for me too (but haven't launch Zwift either to test out so...) Hope that help.

**Comment by sandermvanvliet** [comment]
@ph4r sorry to hear that, could you do me a favour and see if you can find any log files in the `%userprofile%\AppData\Local\Codenizer BV\RoadCaptain` directory? 
If you find any, could you send them to zwift@codenizer.nl then I can see if I can figure out what's happening.

Additionally could you possibly run the command `dotnet --info` and include the output of that in the e-mail?

**Comment by sandermvanvliet** [comment]
@ph4r thanks for the additional logs, I've tracked the issue down to a missing file in the installer.

**Comment by sandermvanvliet** [comment]
Release [0.5.4.0](https://github.com/sandermvanvliet/RoadCaptain/releases/tag/0.5.4.0) has a fix for this problem
