### ISSUE TITLE
Add check new update available + changelog directly at startup

### ISSUE THREAD

**Issue by VNT974** [sandermvanvliet/RoadCaptain#15]
Hello.

Thanks for this quick 0.5.3.0 update, 

Please, could we have a function that automatically detect if a new update is available, and suggest us to download using a button, or redirect to this reddit/releases page, and display changelog ? That would be awesome.

Thanks again.

**Comment by sandermvanvliet** [comment]
Currently that’s by design as I didn’t want any sort of feature that would enable tracking. 

At the same time I’ve been thinking of adding this because it makes it a lot easier to discover a new version. 

Let me take a look at this

**Comment by VNT974** [comment]
Thanks

I indeed kinda like to update when a new update is available, missing fixes, new features is always sad. Ahah.

**Comment by sandermvanvliet** [comment]
This will be in the next release.

**Comment by sandermvanvliet** [comment]
Available as of [0.5.5.0](https://github.com/sandermvanvliet/RoadCaptain/releases/tag/0.5.5.0)
