### ISSUE TITLE
Saving a route, tell me I do not have permission to do it in C/ProgramFiles(x86)/Codenizer BV /RoadCaptain instead create a new folder USER

### ISSUE THREAD

**Issue by VNT974** [sandermvanvliet/RoadCaptain#19]
Saved a route to discover this feature, and RoadCaptain tell me I do not have permission to do it in C/ProgramFiles(x86)/Codenizer BV /RoadCaptain, which was the default (fast) installation of 0.5.3.0 version (after uninstalling 0.5.2.0) as if I understand there are no autocheck for new update at startup #15 

Clicking to NO, RoadCaptain tell me Route saved successfully. Nothing is saved at all.

Why not have a Documents/RoadCaptain folder instead ?

![Screenshot_16](https://user-images.githubusercontent.com/99896027/163123407-5d96566f-4da1-4b82-9366-7322007dc971.png)

**Comment by sandermvanvliet** [comment]
Thanks for reporting this, it seems the default location for saving the route is the working directory of the app which is indeed not writable. 
I’ll make sure it will be set to my documents or similar where this shouldn’t be a problem.

**Comment by sandermvanvliet** [comment]
Will become available in 0.5.4.0
