### ISSUE TITLE
Notification of Added segment/route have the old condusing name template

### ISSUE THREAD

**Issue by VNT974** [sandermvanvliet/RoadCaptain#20]
The real Zwift route/segment names are still the confusing name on the notification bar while it's not when a route/segment is deleted

![Screenshot_18](https://user-images.githubusercontent.com/99896027/163124633-8515fde0-7f92-44a8-ab24-906c63f9ba3e.png)
![Screenshot_19](https://user-images.githubusercontent.com/99896027/163124928-a3f7dfcb-088f-4300-af55-29a608bbedb4.png)

**Comment by sandermvanvliet** [comment]
Heh, missed that one obviously. Thanks for reporting 👍

**Comment by VNT974** [comment]
Hehe no problem, thanks for your fix
