### ISSUE TITLE
Select Zwift World to build a route

### ISSUE THREAD

**Issue by VNT974** [sandermvanvliet/RoadCaptain#21]
Hope that all routes will be available in the future, found it could be great to select a Zwift World first and then Build a route, and probably highlight active World. I believe that at some points user will have to select a map.

Have no clue where WhatsonZwfit get those infos:
![Screenshot_20](https://user-images.githubusercontent.com/99896027/163126242-225b6f4c-5978-421e-a1c8-9abd9d4a7287.png)

**Comment by sandermvanvliet** [comment]
Sneak preview: 
![image](https://user-images.githubusercontent.com/2393265/163671420-0d9e3401-d751-40b2-be5c-1734fbc31526.png)

**Comment by VNT974** [comment]
Amazing.

**Comment by sandermvanvliet** [comment]
This feature will have a first version with Makuri Islands (#7) to test with depending on how easily the segments for that world can be generated.

**Comment by VNT974** [comment]
Thanks so much, This preview is really great and I have some interesting suggestions (tickets will be written later).

What do you think to have 'Select Sport' to be the first choice to make ? Never tried, but Zwift have a Duathlon/Triathlon possibility, 

I would be happy later to have basic settings where I would choose my Sport (Cycling cause I have a HomeTrainer and not a Treadmill that would be annoying to select everytime I use), and same, some people have both, probably let them choose either Cycling or Running after all.

No clue yet how DUathlon work, but if inside a ride we could choose X km done in Cycling, and then switch to X km done in Running it can be great too.

Dunno if there are a sort of Zwift Worlds ranking, but for sure Sorting by popularity would be great.

**Comment by sandermvanvliet** [comment]
Having a default selection for sport is definitely something that needs to be added, most people only have a bike trainer so it doesn't make a lot of sense to always have to click a button to choose cycling every time.

World ranking doesn't really exist AFAIK, order is currently completely arbitrary but I figure the order is going to be something like:

- Watopia
- Makuri Islands
- New York
- London
- the rest...

Purely based on the number of options you have to build a route in that particular world.

Duathlon I'm going to leave out of scope for now.

**Comment by sandermvanvliet** [comment]
As for suggestions, keep them coming!
I would ask to post them here first or perhaps start a [discussion](https://github.com/sandermvanvliet/RoadCaptain/discussions) on it before creating issues (just for the admin side of it 😉)

**Comment by VNT974** [comment]
I also recall about something call Rebel routes, not sure, but that's another sort of routes which is available, same about the Jersey stuff.

**Comment by sandermvanvliet** [comment]
I did create a route for the latest released Rebel Route and tried to get in touch with Eric from Zwift Insider.
Might be nice to add them as "preconfigured" routes indeed.
You can find the latest on [here](https://github.com/sandermvanvliet/RoadCaptain/blob/main/routes/RebelRoute-Epic-Loop.json)

**Comment by VNT974** [comment]
I agree for Preconfigured routes, that would be awesome.

**Comment by sandermvanvliet** [comment]
Now that release 0.6.0.0 is out I'm closing this issue and progress on worlds will be tracked in #7, #12, #17, #18
