### ISSUE TITLE
Cannot OPEN a file if you have already use it.

### ISSUE THREAD

**Issue by VNT974** [sandermvanvliet/RoadCaptain#25]
I was trying the app, added, deleted routes, and EVEN IF there are no route, I am told to SAVE before to OPEN. Don't know if this is a correct behaviour or not, it would be interesting to be able to open a file without to close the app.
![Screenshot_23](https://user-images.githubusercontent.com/99896027/163335417-fa7b8410-44fe-446d-9f10-d6ea43b01259.png)

**Comment by sandermvanvliet** [comment]
There is a check to see if the current route is “tainted” but it seems that this doesn’t reset if you don’t have any segments in the route.
