### ISSUE TITLE
Dialogs shown by Route Builder are not centered to the main window

### ISSUE THREAD

**Issue by VNT974** [sandermvanvliet/RoadCaptain#26]
![Screenshot_23](https://user-images.githubusercontent.com/99896027/163335554-39b0d911-f0cc-4d38-8c39-01d5b40ca9e9.png)

**Comment by sandermvanvliet** [comment]
Could you help me understand what the problem is in this screenshot?

**Comment by VNT974** [comment]
The dialogue box is not centered when itr's a small windows.

**Comment by sandermvanvliet** [comment]
Ok gotcha
