### ISSUE TITLE
Add missing spawn points in Watopia

### ISSUE THREAD

**Issue by sandermvanvliet** [sandermvanvliet/RoadCaptain#34]
~~It seems that there are a few spawn points missing:~~

- [ ] ~~[Tour of fire and ice](https://whatsonzwift.com/world/watopia/route/tour-of-fire-and-ice)~~
- [ ] ~~[Volcano circuit CCW](https://whatsonzwift.com/world/watopia/route/volcano-circuit-ccw)~~
- [ ] ~~[Triple flat loops](https://whatsonzwift.com/world/watopia/route/triple-flat-loops)~~
- [ ] ~~[Serpentine 8](https://whatsonzwift.com/world/watopia/route/serpentine-8)~~
- [ ] ~~[Muir and the Mountain](https://whatsonzwift.com/world/watopia/route/muir-and-the-mountain)~~

~~Additionally there are a few starting segments that can be used in both directions.~~

I got thrown off by the fact that there is a difference between the routes on Whats On Zwift and the actual Zwift routes.
Whats On Zwift shows the route without the lead-in from the spawn point and is therefore a bit confusing.
Zwift Insider has the actual spawn points included.

**Comment by sandermvanvliet** [comment]
Released in version [0.6.1.0](https://github.com/sandermvanvliet/RoadCaptain/releases/tag/0.6.1.0)

**Comment by sigurdhes** [comment]
spawn point of "The Mega Pretzel" is now missing.

Sig

**Comment by sandermvanvliet** [comment]
According to the description of [The mega pretzel](https://zwiftinsider.com/route/the-mega-pretzel/) it indeed starts somewhere else than what the map on that page shows. 

Need to check in-game what happens and if it does start on the land bridge (Volcano to the villas) then it needs to be added back to the spawn points.

**Comment by sigurdhes** [comment]
It starts on the land bridge from Volcano to the Villas:
![image](https://user-images.githubusercontent.com/104097267/164786707-4f1e82e6-4d1a-4809-a519-743fcec6b70a.png)

**Comment by sandermvanvliet** [comment]
It's back:
![image](https://user-images.githubusercontent.com/2393265/164901590-91d8be85-2271-41e2-be2e-1f4535f4d6c1.png)
