### ISSUE TITLE
Add undo last leg button

### ISSUE THREAD

**Issue by sigurdhes** [sandermvanvliet/RoadCaptain#36]
It would be nice to have a "undo last leg" option in the route builder.

**Comment by sandermvanvliet** [comment]
That actually exists! But it’s hard to find right now unfortunately. 

If you select the last segment and hit <kbd>DEL</kbd> it will remove it. Alternatively you can hit <kbd>CTRL</kbd> + <kbd>Z</kbd> which will do the same.

Nevertheless I’ll add a dedicated button for it 👍

**Comment by sigurdhes** [comment]
Super! Discarding a long route for selecting wrong segment was irritating.

**Comment by sandermvanvliet** [comment]
I probably need to add some help functionality to the app by now 🙈
