### ISSUE TITLE
Add spawnpoint

### ISSUE THREAD

**Issue by sigurdhes** [sandermvanvliet/RoadCaptain#38]
"Tour of fire and ice" spawn you inside the volcano at the "Volcano circuit 3" segment going clockwise.

**Comment by sandermvanvliet** [comment]
Spawn point in the volcano has been added as well as a new spawn point in the desert which starts just before the Fuego Flats arch

**Comment by sandermvanvliet** [comment]
![image](https://user-images.githubusercontent.com/2393265/164909388-abef899c-3456-4d46-a913-2165c68c954c.png)

and:

![image](https://user-images.githubusercontent.com/2393265/164909400-8cb154a9-8cf0-4d66-8a63-1623c1bbdd53.png)
