### ISSUE TITLE
Feature: Changing World when nothing is selected

### ISSUE THREAD

**Issue by VNT974** [sandermvanvliet/RoadCaptain#43]
Currently I do use more Watopia as a Default World, but I would like to have a way to choose another World in case I change my mind.

A back arrow ? I guess that would be easy to understand it.
A "Select World" button available when nothing is selected.

Thanks.

**Comment by sandermvanvliet** [comment]
Will be covered by #47

**Comment by sandermvanvliet** [comment]
And only really mean anything when #7 lands 😉

**Comment by VNT974** [comment]
And #12, #16, #17, #18

**Comment by sandermvanvliet** [comment]
As #47 is implemented I’m closing this one
