### ISSUE TITLE
Detailed Route  report

### ISSUE THREAD

**Issue by VNT974** [sandermvanvliet/RoadCaptain#45]
I was trying those  routes incluing a  Sprint segment, where I finally found it could be interesting to have a detailed view about it.
Example Fuego Flatys 1 > 2 > 3 > 4 those selections give 10,2km 17.2D+ and 16.4D-

Speaking that Sprint segment near the Starting point, Fuego Flats Forward Sprint Aka Fuego Flats 3, it's 0.5 km for 0% avg incline.
If I am looking for a Sprint segment name, I would understand better, and KNOW that Fuego Flats Forward Sprint name instad of the other.

Detailed Route steps or report (dunno the adequate name), it would be interesting to include those  Sprint, Kom, Reverse, and their infos about it.

Thanks.

**Comment by sandermvanvliet** [comment]
If I understand you correctly there are two items you'd like to see:

1. Search for a specific KOM/sprint by it's Strava (for lack of better term) segment name
2. Show a list of KOMs and sprints that are on your planned route

Point 1 should be covered by #11 when that will be implemented

Point 2 is something new indeed and has crossed my mind as well. It's kind of related to _show elevation plot_ from #31

**Comment by VNT974** [comment]
I agree to  both points.
I would like to had #51  and #48 as well.

**Comment by VNT974** [comment]
Thanks again for your hard work. Highly positive reviews here.
Have a nice day.
