### ISSUE TITLE
Reset route do not ask me to Save dialogue

### ISSUE THREAD

**Issue by VNT974** [sandermvanvliet/RoadCaptain#52]
Close to #24  I opened a saved route file, made a modification about it, and clicked on  Reset route which did not asked me to  Save the modified work. I would be happy to be asked to save my work.

Thanks.

**Comment by sandermvanvliet** [comment]
Covered by #47 

- Clear route will ask you if you're sure if there are any segments in the route
- World selection will ask you to save if there are any segments in the route
