### ISSUE TITLE
Able to open at the same time 2 windows of RoadCaptain

### ISSUE THREAD

**Issue by VNT974** [sandermvanvliet/RoadCaptain#53]
No clue if this is intended, but I found it nonsense to be able to open 2 same RoadCaptain windows about it
![Screenshot_28](https://user-images.githubusercontent.com/99896027/164960534-a8b68fb3-b376-45f0-9eeb-fd2d64c815a9.png)
.

**Comment by sandermvanvliet** [comment]
No this shouldn’t happen but I haven’t built any checks for this yet. 
Good catch 👍
