### ISSUE TITLE
Fit to Screen button do not work with a minimized screen

### ISSUE THREAD

**Issue by VNT974** [sandermvanvliet/RoadCaptain#55]
![Screenshot_26](https://user-images.githubusercontent.com/99896027/164960922-93700399-fb42-4b85-82cf-ce8458ead0c4.png)

**Comment by sandermvanvliet** [comment]
I'm not sure I understand what you mean. The map is shown completely correct?

Or is your expectation that "fit to screen" means that the Route Builder window is resized to fit the entire screen?

**Comment by VNT974** [comment]
![Screenshot_29](https://user-images.githubusercontent.com/99896027/164965019-050559bc-dc35-4f38-85d8-035820bb1f6a.png)

I have only 8 routes selected here, and this is exactly how it is when I reduce the screen,
The map is not centered, and correctly sized right now. The button are too big, 

I would indeed be happy that the windows match the X number of selected routes, have smaller button 
and more importantly centered (smaller?) map. If I want to reduce more, I could do it manually.

Fit to screen I understand as  centered/reduced if needed map.

**Comment by sandermvanvliet** [comment]
The issue where segments drop off the edges of the map view has been resolved in cfb6cc9a6031241a08a44342cd091e0464a7d1d9 and will be available in [release 0.6.3.0](https://github.com/sandermvanvliet/RoadCaptain/milestone/3)

**Comment by sandermvanvliet** [comment]
The buttons dropping off of the side of the screen when resizing is resolved in ea0517cf5bae45354dcf23110a5a49a9128664c1 and will be in release 0.6.3.0:

![image](https://user-images.githubusercontent.com/2393265/169666395-65804b44-c206-43b1-99c1-4714b1bc3cd7.png)
