### ISSUE TITLE
RoadCaptain misses turn onto Epic KOM to Marina segment from Cliffside segment

### ISSUE THREAD

**Issue by sandermvanvliet** [sandermvanvliet/RoadCaptain#57]
**Describe the issue**
RoadCaptain misses turn onto Epic KOM to Marina segment from Cliffside segment:

Turn is missed and goes onto the direction of the Jungle:

![image](https://user-images.githubusercontent.com/2393265/165096956-5fd1b3aa-a0f2-4c96-abea-3d0c396f5fe6.png)

Route file: [300m in 30km.route.txt](https://github.com/sandermvanvliet/RoadCaptain/files/8554861/300m.in.30km.route.txt)

Reported via e-mail

.

**Comment by sandermvanvliet** [comment]
Looking at the logs it seems that RoadCaptain doesn't detect the upcoming junction but Zwift itself is already there. From earlier testing I remember that Zwift will send you to the Jungle by default when you're coming from the Cliffside segment so what is happening here is that Zwift executes the _default_ turn and RoadCaptain doesn't even see the junction.

**Comment by sandermvanvliet** [comment]
Analysis of the messages sent by Zwift make it appear that when we reach the three-point junction at the end of the Cliffside segment only the left and right turn commands are provided.
I suspect go-straight is implied there and it looks like that is the default direction.
Further in-game testing is needed to see if this is the case from all directions towards this junction.

**Comment by sandermvanvliet** [comment]
This could actually be something in a recent Zwift release as I remember testing this same turn a few times before.

**Comment by sigurdhes** [comment]
I had a similar problem when coming from the Marine and my route was planned onto the cliffside segment. Instead I turned right in the junction towards the Jungle. I had to take a U-turn and manually select the cliffside to be back on route

[roadcaptain-log-2022-04-26T111709.log](https://github.com/sandermvanvliet/RoadCaptain/files/8563577/roadcaptain-log-2022-04-26T111709.log)
.

**Comment by sandermvanvliet** [comment]
Right so that is another little clue that this junction has changed. 
Will be testing a fix later this week for it

**Comment by sandermvanvliet** [comment]
![5E6A1E62-96EF-4B5E-959B-BA1AF57FD434](https://user-images.githubusercontent.com/2393265/165559739-df344d17-9470-49ca-ad42-fe37dd71945d.jpeg)

This now seems to work

**Comment by sigurdhes** [comment]
You are really fast at updating, when one is used to zwift.....
It's a nice feature that, IF there is a faulty turn, you can navigate back with a u-turn, do it manually and still be back on your route.

**Comment by sandermvanvliet** [comment]
Yep that’s why I created #66 to solve that. It’s a bit of a bummer RoadCaptain currently doesn’t help you…
