### ISSUE TITLE
Segment names are long and confusing

### ISSUE THREAD

**Issue by sandermvanvliet** [sandermvanvliet/RoadCaptain#6]
The segment names are now auto generated and have very long names which makes reading them not very great.

The segments should get a more descriptive name, preferably matching the relevant parts of Watopia.

**Comment by VNT974** [comment]
And also matching Zwift official route/segment name. That way Whatsonzwift website could be used to directly search route/segment name.

**Comment by sandermvanvliet** [comment]
Segment names have for the main part all been set to something more friendly for Watopia except for some small connecting segments that I haven't got any inspiration for.

This will be released as part of [0.6.0.0](https://github.com/sandermvanvliet/RoadCaptain/releases/tag/0.6.0.0)
