### ISSUE TITLE
Changelog Windows' hyperlink do not work properly

### ISSUE THREAD

**Issue by VNT974** [sandermvanvliet/RoadCaptain#61]
![Screenshot_31](https://user-images.githubusercontent.com/99896027/165215353-822084b4-404d-4bcb-bcaa-b6c7b2a3221e.png)

**Comment by sandermvanvliet** [comment]
Yep this was very MVP 😅

I need to find a Markdown component to show this properly.

**Comment by sandermvanvliet** [comment]
Found a possible component: https://github.com/whistyun/Markdown.Avalonia

**Comment by sandermvanvliet** [comment]
We now have a properly formatted changelog:

![image](https://user-images.githubusercontent.com/2393265/169667040-a46aebd5-c2b9-419a-af1f-92b49b913771.png)
