### ISSUE TITLE
Return to start screen when ending activity in Zwift

### ISSUE THREAD

**Issue by sandermvanvliet** [sandermvanvliet/RoadCaptain#67]
Currently RoadCaptain remains on the in-game screen when you end an activity in Zwift. 

In the case where you want to select a different route to ride/run you now first have to exit RoadCaptain, start it again, log in to Zwift, select the new route and then start a new activity in Zwift.

That’s not a very nice experience. 

To improve that, RoadCaptain should return to the start screen automatically when you end an activity in Zwift.

**Comment by VNT974** [comment]
Do you have a way to select a saved route directly without to minimize Zwift ? Something similar to GTA Bike V
https://fr.gta5-mods.com/scripts/gt-bike-v

This overlay things is pretty awesome, I imagine some alternative better map than the Vanilla, in fact Zwift HUD is still ugly.

**Comment by sandermvanvliet** [comment]
Implemented in e836bc22ffc4b3b1b3fa0418716536f1d6aac840 but still needs some testing.

**Comment by sandermvanvliet** [comment]
Verified this works.
