### ISSUE TITLE
Hilly KOM bypass turn missed

### ISSUE THREAD

**Issue by Slothful1** [sandermvanvliet/RoadCaptain#72]
I created a route to start Downtown, go over Hilly KOM, and then turn right onto Hilly KOM bypass so I could do the Hilly KOM Bypass Loop rebel route, followed by a route to the Italian village to do a loop of the Italian Village Sprint Loop rebel route, before finishing Downtown.

After the Hilly KOM, the right turn onto the bypass was ignored, but I caught it in time and made the turn manually.  The right turn onto Hilly KOM segment was fine, and most of the remaining turns were OK.  I wasn't paying proper attention to make notes but I seem to remember another missed turn later (attempt to turn to Volcano instead of through village to Sprint I think), which I also caught in time.

Otherwise a fantastic product that I've enjoyed using this past week (and thanks for fixing the Sequoia circle turn issue before I got to reporting it on v0.6.1).

Thanks
Dave

**Application details:**
- Zwift version = 1.24.2
- Zwift device = desktop PC
- Road Captain version = 0.6.2.1

**Additional info**
[Log.txt](https://github.com/sandermvanvliet/RoadCaptain/files/8598688/Log.txt)
[Rebel Route double - Hilly KOM Bypass Loop plus Italian Villas Sprint Loop.json.txt](https://github.com/sandermvanvliet/RoadCaptain/files/8598690/Rebel.Route.double.-.Hilly.KOM.Bypass.Loop.plus.Italian.Villas.Sprint.Loop.json.txt)
[roadcaptain-log-2022-04-30T150544.log](https://github.com/sandermvanvliet/RoadCaptain/files/8598691/roadcaptain-log-2022-04-30T150544.log)

**Comment by Slothful1** [comment]
I rerode the route yesterday.  I can confirm that the 2nd missed turn was as I said above - at the Italian village fountain it tried to send me straight to Volcano so I had to route manually right to go to the sprint.

**Comment by sandermvanvliet** [comment]
All right, thanks for re testing that 👍
Let me see if I can replicate it here too (should be the case) and debug it

**Comment by sandermvanvliet** [comment]
The second missed turn was also reported in #84 and is now fixed and will be released in 0.6.4.0 👍

**Comment by sandermvanvliet** [comment]
@Slothful1 I've retested the route again and it's now working as expected including the hilly KOM bypass turn :+1:
