### ISSUE TITLE
missed turn from Marina to cliffside

### ISSUE THREAD

**Issue by sigurdhes** [sandermvanvliet/RoadCaptain#73]
I have reported this before, but opening a new issue.
I was coming from the Marine and was planning to go onto the cliffside, but the selected turn was toward the jungle.

Se picture:
![image](https://user-images.githubusercontent.com/104097267/166157148-a18c4a14-3b0c-4edd-b099-75a22b5adf7b.png)

Running roadcaptain 0.2.6.1 and zwift 1.24.2 on a MS surface

Logfile:
[roadcaptain-log-2022-05-01T124551.log](https://github.com/sandermvanvliet/RoadCaptain/files/8599403/roadcaptain-log-2022-05-01T124551.log)

Route:
{
  "version": "1",
  "route": {
    "name": "RoadCaptain route starting on The Mega Pretzel",
    "zwiftRouteName": "The Mega Pretzel",
    "hasCompleted": false,
    "hasStarted": false,
    "segmentSequenceIndex": 0,
    "startingSegmentId": "watopia-bambino-fondo-004-before-before",
    "nextSegmentId": null,
    "turnToNextSegment": "none",
    "currentSegmentId": null,
    "routeSegmentSequence": [
      {
        "segmentId": "watopia-bambino-fondo-004-before-before",
        "turnToNextSegment": "right",
        "nextSegmentId": "watopia-bambino-fondo-001-after-after-after-before",
        "direction": "btoA"
      },
      {
        "segmentId": "watopia-bambino-fondo-001-after-after-after-before",
        "turnToNextSegment": "right",
        "nextSegmentId": "watopia-bambino-fondo-001-after-after-before-after",
        "direction": "btoA"
      },
      {
        "segmentId": "watopia-bambino-fondo-001-after-after-before-after",
        "turnToNextSegment": "right",
        "nextSegmentId": "watopia-bambino-fondo-003-before-before",
        "direction": "btoA"
      },
      {
        "segmentId": "watopia-bambino-fondo-003-before-before",
        "turnToNextSegment": "left",
        "nextSegmentId": "watopia-ocean-lava-cliffside-loop-001",
        "direction": "atoB"
      },
      {
        "segmentId": "watopia-ocean-lava-cliffside-loop-001",
        "turnToNextSegment": "left",
        "nextSegmentId": "watopia-big-loop-rev-001-after-after",
        "direction": "atoB"
      },
      {
        "segmentId": "watopia-big-loop-rev-001-after-after",
        "turnToNextSegment": "goStraight",
        "nextSegmentId": "watopia-big-foot-hills-003-after",
        "direction": "atoB"
      },
      {
        "segmentId": "watopia-big-foot-hills-003-after",
        "turnToNextSegment": "left",
        "nextSegmentId": "watopia-bambino-fondo-001-after-after-before-before-after-after",
        "direction": "atoB"
      },
      {
        "segmentId": "watopia-bambino-fondo-001-after-after-before-before-after-after",
        "turnToNextSegment": "goStraight",
        "nextSegmentId": "watopia-bambino-fondo-001-after-after-before-after",
        "direction": "atoB"
      },
      {
        "segmentId": "watopia-bambino-fondo-001-after-after-before-after",
        "turnToNextSegment": "goStraight",
        "nextSegmentId": "watopia-bambino-fondo-002-after",
        "direction": "atoB"
      },
      {
        "segmentId": "watopia-bambino-fondo-002-after",
        "turnToNextSegment": "left",
        "nextSegmentId": "watopia-beach-island-loop-004",
        "direction": "btoA"
      },
      {
        "segmentId": "watopia-beach-island-loop-004",
        "turnToNextSegment": "left",
        "nextSegmentId": "watopia-bambino-fondo-001-after-after-after-after-before-before",
        "direction": "btoA"
      },
      {
        "segmentId": "watopia-bambino-fondo-001-after-after-after-after-before-before",
        "turnToNextSegment": "goStraight",
        "nextSegmentId": "watopia-bambino-fondo-001-after-after-after-before",
        "direction": "btoA"
      },
      {
        "segmentId": "watopia-bambino-fondo-001-after-after-after-before",
        "turnToNextSegment": "right",
        "nextSegmentId": "watopia-bambino-fondo-001-after-after-before-after",
        "direction": "btoA"
      },
      {
        "segmentId": "watopia-bambino-fondo-001-after-after-before-after",
        "turnToNextSegment": "goStraight",
        "nextSegmentId": "watopia-bambino-fondo-001-after-after-before-before-after-after",
        "direction": "btoA"
      },
      {
        "segmentId": "watopia-bambino-fondo-001-after-after-before-before-after-after",
        "turnToNextSegment": "right",
        "nextSegmentId": "watopia-big-foot-hills-003-after",
        "direction": "btoA"
      },
      {
        "segmentId": "watopia-big-foot-hills-003-after",
        "turnToNextSegment": "goStraight",
        "nextSegmentId": "watopia-big-loop-rev-001-after-after",
        "direction": "btoA"
      },
      {
        "segmentId": "watopia-big-loop-rev-001-after-after",
        "turnToNextSegment": "right",
        "nextSegmentId": "watopia-ocean-lava-cliffside-loop-001",
        "direction": "btoA"
      },
      {
        "segmentId": "watopia-ocean-lava-cliffside-loop-001",
        "turnToNextSegment": "right",
        "nextSegmentId": "watopia-bambino-fondo-003-before-before",
        "direction": "btoA"
      },
      {
        "segmentId": "watopia-bambino-fondo-003-before-before",
        "turnToNextSegment": "left",
        "nextSegmentId": "watopia-bambino-fondo-001-after-after-before-after",
        "direction": "btoA"
      },
      {
        "segmentId": "watopia-bambino-fondo-001-after-after-before-after",
        "turnToNextSegment": "goStraight",
        "nextSegmentId": "watopia-bambino-fondo-002-after",
        "direction": "atoB"
      },
      {
        "segmentId": "watopia-bambino-fondo-002-after",
        "turnToNextSegment": "goStraight",
        "nextSegmentId": "watopia-bambino-fondo-002-before-after-after",
        "direction": "btoA"
      },
      {
        "segmentId": "watopia-bambino-fondo-002-before-after-after",
        "turnToNextSegment": "goStraight",
        "nextSegmentId": "watopia-bambino-fondo-002-before-after-before",
        "direction": "btoA"
      },
      {
        "segmentId": "watopia-bambino-fondo-002-before-after-before",
        "turnToNextSegment": "left",
        "nextSegmentId": "watopia-climbers-gambit-001",
        "direction": "btoA"
      },
      {
        "segmentId": "watopia-climbers-gambit-001",
        "turnToNextSegment": "left",
        "nextSegmentId": "watopia-bambino-fondo-002-before-before-before",
        "direction": "atoB"
      },
      {
        "segmentId": "watopia-bambino-fondo-002-before-before-before",
        "turnToNextSegment": "goStraight",
        "nextSegmentId": "watopia-bambino-fondo-001-after-before",
        "direction": "btoA"
      },
      {
        "segmentId": "watopia-bambino-fondo-001-after-before",
        "turnToNextSegment": "goStraight",
        "nextSegmentId": "watopia-bambino-fondo-001-after-after-after-after-after-after",
        "direction": "btoA"
      },
      {
        "segmentId": "watopia-bambino-fondo-001-after-after-after-after-after-after",
        "turnToNextSegment": "goStraight",
        "nextSegmentId": "watopia-bambino-fondo-001-after-after-after-after-after-before",
        "direction": "btoA"
      },
      {
        "segmentId": "watopia-bambino-fondo-001-after-after-after-after-after-before",
        "turnToNextSegment": "right",
        "nextSegmentId": "watopia-beach-island-loop-001",
        "direction": "btoA"
      },
      {
        "segmentId": "watopia-beach-island-loop-001",
        "turnToNextSegment": "left",
        "nextSegmentId": "watopia-bambino-fondo-004-before-after",
        "direction": "atoB"
      },
      {
        "segmentId": "watopia-bambino-fondo-004-before-after",
        "turnToNextSegment": "none",
        "nextSegmentId": null,
        "direction": "btoA"
      }
    ],
    "world": "watopia",
    "sport": "cycling"
  }
}

**Comment by iilis** [comment]
I have a route that does this turn as well and it seemed to work after the 0.6.3.1 update (most recent).

**Comment by sandermvanvliet** [comment]
I've added special handling for this junction as Zwift only returns 2 of the 3 available turns and it depends on which way you approach the junction whether you'll get left/right, left/gostraight or right/gostraight...

Will do some game testing but it should now be fixed for all segments approaching this junction.
