### ISSUE TITLE
Missed Turn onto Volcano Climb

### ISSUE THREAD

**Issue by iilis** [sandermvanvliet/RoadCaptain#77]
**Describe the issue**
Runner missed turn from Volcano Circuit 1 to Volcano Climb.
This route starts in downtown Watopia (using the Beach Island Loop route as the basis).  When on Volcano Circuit 1, Zwift routing was going to continue around the Volcano Circuit but I caught it before the turn and went up  the climb.  When ‘playing’ the route in the Builder, it runs up the climb and back down just fine.

**Application details:**
To help troubleshoot the issue please provide:
- Zwift version : 1.25.1
- Zwift device : Windows 10 PC
- Road Captain version : 0.6.2.1

**Additional info**
- Tried to attach JSON file, but GitHub said file type not supported.

**Comment by sandermvanvliet** [comment]
Hi @iilis thanks for reporting this. 
Could you email the route file and the log files to zwift@codenizer.nl? 
That will help troubleshooting 🙂

**Comment by iilis** [comment]
Attaching log files
(Put a .txt extension the JSON file to upload it.)

[DragonVsTitan.json.txt](https://github.com/sandermvanvliet/RoadCaptain/files/8742424/DragonVsTitan.json.txt)
[roadcaptain-log-2022-05-19T200410.log](https://github.com/sandermvanvliet/RoadCaptain/files/8742423/roadcaptain-log-2022-05-19T200410.log)
[Log.txt](https://github.com/sandermvanvliet/RoadCaptain/files/8742425/Log.txt)

**Comment by iilis** [comment]
Created my own version of the Three Little Sisters rebel route and encountered the same issue.
> Visual problem in the Runner is when the it misses the turn on the "Volcano Climb (ascent)", when climbing it shows that I'm on "Volcano Climb (descent)", it skips "Volcano Summit", then shows "Volcano Climb (descent)" again.

Here are the files
[RebelRoute-ThreeLittleSisters.json.txt](https://github.com/sandermvanvliet/RoadCaptain/files/8749677/RebelRoute-ThreeLittleSisters.json.txt)
[roadcaptain-log-2022-05-22T132631.log](https://github.com/sandermvanvliet/RoadCaptain/files/8749678/roadcaptain-log-2022-05-22T132631.log)
[Log_2022-05-22.txt](https://github.com/sandermvanvliet/RoadCaptain/files/8749679/Log_2022-05-22.txt)

**Comment by sandermvanvliet** [comment]
I’m finalising the 0.6.3.0 release which should free up time to look at these issues.

**Comment by sandermvanvliet** [comment]
I’ve found some issues with the positioning especially around the volcano area as there are many segments overlapping each other. 

I’m now working on making that algorithm smarter so it doesn’t get confused by segments that are at a different elevation than the segment you’re currently on. 

Right now what you can see happening is that when you are on volcano circuit 1 and ride into the volcano that RoadCaptain loses the route lock (red screen is shown). That is because it _thinks_ it’s already on the volcano climb segment that is above it….

**Comment by iilis** [comment]
Thanks for the update.
I tried my routes (above) in the 0.6.3.1 release and they were both pretty wonky around the Volcano.  (Just been busy and hadn’t had a chance to report it.)
I figured the issue had to with a location positioning that didn’t take overlap routes into account.  Thinking about, I don’t think there are many of those in Zwift at all (maybe a 1-2 in NeoTokyo?).  But if you can figure out a way to address it, it should work on any such route in the future.

Thanks for your continued work on this app!

**Comment by sandermvanvliet** [comment]
I've fixed it, running some additional tests with your route and a test route I just built specifically for this.
This will be included in the 0.6.4.0 release 👍

**Comment by sandermvanvliet** [comment]
![5796DDBB-D8AA-431C-A336-0A694E638BAE](https://user-images.githubusercontent.com/2393265/175399401-262c3e84-334d-4cc0-a16f-a14c17bc1496.jpeg)

Heading up the Volcano as expected using the route you’ve built 👍

**Comment by iilis** [comment]
Thanks!
