### ISSUE TITLE
Incorrect Turn Data Sequoia to Epic and Ocean Boulevard 1

### ISSUE THREAD

**Issue by PhilipAmos** [sandermvanvliet/RoadCaptain#85]
**Describe the issue**
When riding "Sequoia to Epic" atoB the Road Captain wanted to go Straight but the actual options are Left and Right and the choice should have been Right

When riding "Ocean Boulevard 1" btoA Road Captain wanted to go Straight but the actual options are Left and Right and the choice should have been Right

I have uploaded a TXT file with the turns that need changing, I have put RIGHT in capitals so it stands out.  I have tested this change and my screenshots show the correct turn after I manually changed.

I have uploaded a couple of screenshots showing the turn choices in game of the areas.

**Application details:**
To help troubleshoot the issue please provide:
- Zwift version - 1.25.2(101024)
- Windows 11 (Do you run Zwift on a desktop PC, AppleTV or iOS)
- 0.6.2.1

**Additional info**
To help troubleshoot the issue please attach:
![2022-05-31 (9)](https://user-images.githubusercontent.com/106473361/171270712-8bc5cd4f-f637-4be4-86b6-ca0191d62180.png)
![2022-05-31 (11)](https://user-images.githubusercontent.com/106473361/171270718-b9e7f95c-236f-4b45-98d1-9e3a21b66e93.png)
[turns-watopia update.txt](https://github.com/sandermvanvliet/RoadCaptain/files/8808850/turns-watopia.update.txt)
[Epic KOM Reverse.txt](https://github.com/sandermvanvliet/RoadCaptain/files/8808856/Epic.KOM.Reverse.txt)

- The route file you used
- The RoadCaptain log files (see the directory: `%userprofile%\AppData\Local\Codenizer BV\RoadCaptain`)
- Last Zwift log file (usually these live here: `My Documents\Zwift\Logs`)

If you have a screenshot or screen recording of the issue that always helps :+1:

**Comment by sandermvanvliet** [comment]
Oh wow that’s just the tool I need. With the weather being nice again I don’t ride indoors now so troubleshooting doesn’t happen as quickly 😅

**Comment by PhilipAmos** [comment]
Here is the link to it.  You need 2 ANT+ USB devices, one broadcasts and the other receives.  I add a ""Bike Power Sensor (Power Only)" and set it to 90 RPM and 200 or 250 watts and then it just broadcasts power just like a Power Meter.

https://www.thisisant.com/news/simulant-next-generation-ant-simulation-tool-now-available/

**Comment by sandermvanvliet** [comment]
Small update:

I’ve ordered the ANT+ dongles and they should be delivered in the next few days. 

Thanks to @Slothful1 for sponsoring RoadCaptain and making this possible 👍

**Comment by sandermvanvliet** [comment]
@PhilipAmos I've received the ANT+ dongles and while I can get them to receive data (tested with my HR monitor) setting them up to simulate (and send) data doesn't seem to work.

I've downloaded SimulANT+ and added a single dongle and configured it with the sensor you suggested. Then I tried to use my Garmin Forerunner watch to see if I could pick up the sensor but no dice.

Did you have to do any special magic to make it work?

**Comment by sandermvanvliet** [comment]
After some searching on the official ANT+ forums it looks like the Cycplus dongles I have are nerfed and don't work...
https://www.thisisant.com/forum/viewthread/7293/ has more details.

Guess I'll be ordering the official Garmin one.

**Comment by PhilipAmos** [comment]
That's annoying.  I have the Garmin Dongles as I got one years ago included with my Garmin Vector 2's and when I started indoor cycling when Zwift was in Beta you didn't get any choice so I bought another forgetting I already had one.

**Comment by sandermvanvliet** [comment]
A Garmin one is now on the way so I should be in business hopefully end of the week

**Comment by PhilipAmos** [comment]
Excellent.  It will make testing quite a lot easier.

**Comment by sandermvanvliet** [comment]
I have just tested the fixes for this in-game and they work 👍 
Will be released in 0.6.4.0
