### ISSUE TITLE
Move "Route name" textbox to a better location

### ISSUE THREAD

**Issue by VNT974** [sandermvanvliet/RoadCaptain#9]
Hello.

A little improvment I would like to suggest is to move that 'Route name search' on top of the Windows, its easier to discover and userfriendly.

Thanks.

![Screenshot_15](https://user-images.githubusercontent.com/99896027/162949993-d0fd66a6-bad7-4875-8501-18514f70429c.png)

**Comment by sandermvanvliet** [comment]
Agree. I've added that text box there as a way to provide a name for the route you're building.
It gets saved and then is used in the Runner to display it so you can recognize routes easier.

But as I'm a back-end developer mostly I shouldn't be trusted to design proper UI's 😉
