### ISSUE TITLE
Enhancement to "Start another loop at end of route"

### ISSUE THREAD

**Issue by PhilipAmos** [sandermvanvliet/RoadCaptain#95]
**Is your feature request related to a problem? Please describe.**
I like the idea of the "Start another loop at end of route" option but this only works if your route is a big loop.

What I would like to be able to do is do a lead in to a loop and then loop around that loop.

**Describe the solution you'd like**
Get the option to choose "Start another loop at end of route" for a route that has a lead in to a loop.

**Describe alternatives you've considered**
At the moment you have to keep plotting the loop which means you have to know in advance how many loops you will be performing.

**Additional context**
Here is an example of a loop with a lead in that I ike to ride.:

{
  "version": "2",
  "roadCaptainVersion": "0.6.4.0",
  "route": {
    "name": "RoadCaptain route starting on Big Loop",
    "zwiftRouteName": "Big Loop",
    "isLoop": false,
    "routeSegmentSequence": [
      {
        "segmentId": "watopia-bambino-fondo-001-after-after-after-after-after-before",
        "turnToNextSegment": "goStraight",
        "nextSegmentId": "watopia-bambino-fondo-001-after-after-after-after-after-after",
        "direction": "atoB"
      },
      {
        "segmentId": "watopia-bambino-fondo-001-after-after-after-after-after-after",
        "turnToNextSegment": "goStraight",
        "nextSegmentId": "watopia-bambino-fondo-001-after-before",
        "direction": "atoB"
      },
      {
        "segmentId": "watopia-bambino-fondo-001-after-before",
        "turnToNextSegment": "goStraight",
        "nextSegmentId": "watopia-bambino-fondo-002-before-before-before",
        "direction": "atoB"
      },
      {
        "segmentId": "watopia-bambino-fondo-002-before-before-before",
        "turnToNextSegment": "goStraight",
        "nextSegmentId": "watopia-bambino-fondo-002-before-before-after",
        "direction": "atoB"
      },
      {
        "segmentId": "watopia-bambino-fondo-002-before-before-after",
        "turnToNextSegment": "right",
        "nextSegmentId": "watopia-climbers-gambit-001",
        "direction": "atoB"
      },
      {
        "segmentId": "watopia-climbers-gambit-001",
        "turnToNextSegment": "none",
        "nextSegmentId": null,
        "direction": "atoB"
      }
    ],
    "world": "watopia",
    "sport": "cycling"
  }

**Comment by sandermvanvliet** [comment]
I like this 👍

**Comment by PhilipAmos** [comment]
I think the second one looks good.

**Comment by sandermvanvliet** [comment]
Lead in segments are shown with a dashed line on the map too: 
![image](https://user-images.githubusercontent.com/2393265/177799535-80096a52-b06f-43ae-be39-9dca1d322b10.png)

**Comment by sandermvanvliet** [comment]
It’s looking good. Going to test a few more things to make sure the loop count works as expected.

**Comment by sandermvanvliet** [comment]
All good, this will be in release 0.6.6.0 :+1:
