### ISSUE TITLE
Perform U-Turns

### ISSUE THREAD

**Issue by PhilipAmos** [sandermvanvliet/RoadCaptain#96]
**Is your feature request related to a problem? Please describe.**
It would be nice if you could choose a start point for instance "Epic to Jungle" and rather than heading towards the Jungle area RoadCaptain performs a U-Turn so you are heading towards The "Epic KOM 3/Epic KOM to Marina" Junction.

Performing a U-Turn could potentially be useful though on any section not just the start sections.

**Describe the solution you'd like**
Maybe in the Route Builder you could have a U-Turn checkbox next to the Section Name in the Section List.  When checked you would then be able to select a Section that you would be able to navigate to if you had of perrformed the U-Turn.

**Describe alternatives you've considered**
I've not tried anything else.

**Additional context**
None.

**Comment by sandermvanvliet** [comment]
Good suggestion, it’s already covered by #42 so I’ll close this issue in favour of that one 👍
