### ISSUE TITLE
RoadCaptain Runner crashed during session

### ISSUE THREAD

**Issue by Slothful1** [sandermvanvliet/RoadCaptain#97]
Hi

This evening I've tried running v0.6.4.0 for the first time.  I normally start RoadCaptain Runner before opening Zwift, but I forgot this time and opened it while Zwift was already on the route selection screen.  It looked OK though, and moved from the start screen to the list of segments once I'd selected the recommended start route in-game.

After a couple of minutes I noticed that RoadCaptain wasn't in its usual position on my second screen, but just assumed it had gone behind the browser window.  It turns out that it had closed itself and wasn't just hidden.  I didn't see any error boxes, and it just closed silently.

I'm on v1.26.2 (101236) of the Zwift app, and had just rebooted my desktop before starting the session.  I've attached the RoadCaptain and Zwift logfiles below.  

I'll test things again when I do a session on Tuesday.

Dave
[roadcaptain-runner-log-2022-07-03T142041.log](https://github.com/sandermvanvliet/RoadCaptain/files/9035350/roadcaptain-runner-log-2022-07-03T142041.log)
[Log.txt](https://github.com/sandermvanvliet/RoadCaptain/files/9035351/Log.txt)

**Comment by sandermvanvliet** [comment]
Thanks for reporting this one. I’ve seen this exact error occasionally happen before on my development machine but as I hadn’t been able to reproduce it reliably I figured it had something to do with running under a debugger. 

Based on your log files I see that it happens on a release build too. 

Will investigate this when I’m able 👍

**Comment by sandermvanvliet** [comment]
@Slothful1 after a long long time I've tracked down the issue and fixed it in fb5eed080debcf7cd15554b86609f28e781730f1 :+1:
