### ISSUE TITLE
New Zwift version (1.27) breaks RoadCaptain

### ISSUE THREAD

**Issue by sandermvanvliet** [sandermvanvliet/RoadCaptain#99]
With the new Zwift update it’s looking like turn commands don’t work anymore which effectively breaks RoadCaptain. 

This problem also occurs with Zwift Companion so it seems not directly related to Road Captain, however I’m not sure yet. 

Currently I’m investigating this issue as well as the new connection changes in Zwift itself. 

Hopefully the next release of Road Captain addresses these issues and you can use the app normally again. 

Unfortunately I can’t provide any timeline yet, I would like to ask a bit of your patience while I sort this out. 

If you have any feedback please comment on this issue 👍

**Comment by sandermvanvliet** [comment]
This was _sort of_ announced in #91 but I did not expect it to have this effect as RoadCaptain is still using the legacy connection.

**Comment by oldnapalm** [comment]
Companion app is broken too (Android at least), looks like only left and right commands work, straight and U-turn don't.

**Comment by sandermvanvliet** [comment]
Yes I’ve found that as well, see also my post on the Zwift forums [here](https://forums.zwift.com/t/turn-commands-flaky-when-using-zwift-companion/586977/5)

**Comment by sandermvanvliet** [comment]
Good news, RoadCaptain now supports the encrypted connection introduced in Zwift 1.27.

A new release will be out soon!

**Comment by VNT974** [comment]
Congratulation for this huge huge support. Keep the hard work !

**Comment by sandermvanvliet** [comment]
@oldnapalm I've documented the encryption process here: https://github.com/sandermvanvliet/RoadCaptain/blob/main/docs/ZwiftEncryption.md
If you’ve got any feedback that would be appreciated 👍

**Comment by oldnapalm** [comment]
> @oldnapalm I've documented the encryption process here: https://github.com/sandermvanvliet/RoadCaptain/blob/main/docs/ZwiftEncryption.md If you’ve got any feedback that would be appreciated 👍

Nice work. I have only experimented with communication between game and server (zoffline) but I think this applies to companion as well, the connection id (IV bytes 6-7) is incremented and the seqno (counter) is reset if the connection is closed. But since communication between game and companion is over LAN this will probably never happen.

**Comment by sandermvanvliet** [comment]
Ah great, I wondered what that was for. I’ll update the docs. 

So far I’ve not seen the connection drop between Zwift and ZC on LAN. Theoretically it could happen on wifi as that can see disconnects more than a wired network

**Comment by sandermvanvliet** [comment]
@oldnapalm I've updated the docs and also included a note on the endianness of the bytes. That threw me off when implementing this...

**Comment by oldnapalm** [comment]
One thing that triggers TCP reconnection (connection ID increment and seqno reset) in ZwiftApp is leaving a world and joining another.

**Comment by sandermvanvliet** [comment]
Right, I’ll go test that and see what happens 👍

**Comment by sandermvanvliet** [comment]
Testing so far shows that it seems to work all right now that #98 has been fixed so I’m closing this issue 👍
